parameters:

- name: statusContext
  type: string 
  default: 'Windows Integration Tests'

steps:

- checkout: self
- checkout: maccore
  persistCredentials: true  # hugely important, else there are some scripts that check a single file from maccore that will fail

- pwsh : |
    gci env: | format-table -autosize -wrap
  displayName: 'Dump Environment'

- task: ChocolateyToolInstaller@1
  displayName: 'Install Chocolatey'

- pwsh: |
    Write-Host "Installing dependecies"
    choco install 7zip.install --pre
  displayName: 'Install Dependencies'

- task: DownloadPipelineArtifact@2
  displayName: Download Windows tests
  inputs:
    patterns: '**/dotnet-test-package.7z'
    allowFailedBuilds: true
    path: $(Build.SourcesDirectory)/artifacts/tmp

- pwsh: |
    ls -Rla $(Build.SourcesDirectory)/artifacts/tmp
    7z x $(Build.SourcesDirectory)/artifacts/tmp/dotnet-test-package/dotnet-test-package.7z -o$(Build.SourcesDirectory)/artifacts/ -bb1
    ls -Rla $(Build.SourcesDirectory)/artifacts/dotnet-test-package
  displayName: Expand tests.
